# This is a basic workflow to help you get started with Actions

name: Fivem Natives Mock

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Concatenate client
        run: cat client/cfx.lua client/vehicle.lua > bin/client.lua

      - name: Concatenate server
        run: cat server/cfx.lua > bin/server.lua
